### ISSUE TITLE
Highlight current nav-item in sidebar-menu to improve overview

### ISSUE THREAD

**Issue by escapedcat** [sumcumo/nuxt-styleguide#11]
https://sumcumo.github.io/nuxt-styleguide/docs/configuration/
![image](https://user-images.githubusercontent.com/1016218/40708557-05944c1e-63f4-11e8-8f10-a763c9da93d4.png)

Here *Configuration* in the left sidebar should be highlighted in a way.  
If navigating through a long list of components it's easy to get lost where you actually are.

**Comment by Xiphe** [comment]
released with `@sum.cumo/nuxt-styleguide@5.2.1`
