### ISSUE TITLE
Use prism.js as code highlighter

### ISSUE THREAD

**Issue by HerrBertling** [sumcumo/nuxt-styleguide#15]
The code highlighting is a bit plain right now. I want to change this.

I liked prism.js in the design system I helped build at Xing. It looks quite nice, is easy to integrate (=> https://www.yasminzy.com/tutorial/prism.html#installation ) and if we're very bored, we could even build an own theme for it. Which isn't even that hard to accomplish :)

Would look similar to this:

![image](https://user-images.githubusercontent.com/1827373/48147214-0ffe0b80-e2b7-11e8-829f-48c5299a7e72.png)

![image](https://user-images.githubusercontent.com/1827373/48147245-2015eb00-e2b7-11e8-8864-bd903519421b.png)

**Comment by lassediercks** [comment]
Can only recommend prism, works like a charm
