### ISSUE TITLE
Fix usage of Nuxt.Options/Nuxt.Utils

### ISSUE THREAD

**Issue by HerrBertling** [sumcumo/nuxt-styleguide#16]
Apparently, the API usage introduced in https://github.com/sumcumo/nuxt-styleguide/commit/392dfdfb07587dc18d396f9a262b044a4938cb2d#diff-9fb54c666ef3230de38f8308486a0d6d is not valid anymore with the current nuxt-version (`2.3.0-25694505.cf1aa1a`) – I got an error on `yarn start` when using the project in the current state:

```sh
$ yarn start
yarn run v1.12.3
$ cd demo && yarn start $1
$ nuxt
Options undefined                                                                                        11:05:38

 FATAL  [                                                                                                11:05:38
  /Users/markussiering/Sites/nuxt-styleguide/packages/nuxt-styleguide-config/nuxtStyleguideConfig.js:1
  TypeError: Cannot read property 'from' of undefined
      at Object.<anonymous> (/Users/markussiering/Sites/nuxt-styleguide/packages/nuxt-styleguide-config/nuxtStyleguideConfig.js:59:26)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
]


   ╭─────────────────────────────────────────────────────────╮
   │                                                         │
   │   ✖ Nuxt Fatal Error                                    │
   │                                                         │
   │   TypeError: Cannot read property 'from' of undefined   │
   │                                                         │
   ╰─────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I did a `console.log("Options", Options)` which you might notice. And as you'll notice as well, `Options` is undefined.

I couldn't find a quick replacement for this.

`Utils` is undefined as well – doing a plain `require('nuxt')` offers this:

```
$ nuxt
NuxtImport:  {                                                                                           11:17:50
  Module: [Function: ModuleContainer],
  Nuxt: [Function: Nuxt],
  Resolver: [Function: Resolver],
  Builder: [Function: Builder],
  Generator: [Function: Generator]
}
NuxtImport Utils:  undefined
```

I do not have deep knowledge of the Nuxt@2 API – maybe someone could help here?

Side note: I got this to work by reverting to the `module.export = Object.assign(…)` part that was changed in the commit (and removing the `Options.defaults` which of course is also undefined. Since `Utils` is undefined as well, I guess that's not a very thorough solution, though :D

Maybe @Xiphe or @escapedcat have an idea about what to do here?

**Comment by HerrBertling** [comment]
Hm, according to the docs, both are available: https://nuxtjs.org/api/internals#utils & right below https://nuxtjs.org/api/internals#options 🤔

I'll check what's going wrong there.

**Comment by Xiphe** [comment]
Not sure about this. Nuxt API stability and documentation really is a pita. You probably have to check the nuxt.js source code and trust it more than the documentation.
On the other hand the maintainers are really open for contributions which then makes it quite easy to fix stuff :)

**Comment by HerrBertling** [comment]
FYI: https://cmty.app/nuxt/nuxtjs.org/issues/c150
