### ISSUE TITLE
migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by escapedcat** [sumcumo/nuxt-styleguide#18]
Warning in CircleCI says:
> Projects currently running on CircleCI 1.0 are no longer supported. Please migrate to CircleCI 2.0.

**Comment by HerrBertling** [comment]
Where did you see that warning? Seems to me that we're using 2.0 already:

![image](https://user-images.githubusercontent.com/1827373/48203076-d1278e80-e366-11e8-85b6-b4036064f745.png)

**Comment by escapedcat** [comment]
![image](https://user-images.githubusercontent.com/1016218/48203560-1b5d3f80-e368-11e8-95c1-bfe1f984e164.png)
Well that was confusing. Cool!
