### ISSUE TITLE
Question: Possible to add special styling to `component-demo` divs for styleguide-states?

### ISSUE THREAD

**Issue by escapedcat** [sumcumo/nuxt-styleguide#6]
I have a transparent button with white text.  
Would it be possible to add special styling to the `component-demo` div? Like a `background-color` and `padding` for example.

![image](https://user-images.githubusercontent.com/1016218/40436954-64b61398-5eb4-11e8-8a29-8a7446a6083d.png)

In this example I added the `background-color` via devtools.

**Comment by Xiphe** [comment]
Yeah, this is also relevant for absolute positioning and much more.

I would suggest to add `demoStyle` to the `styleguide-states` and maybe even a `demoRender` method.
