### ISSUE TITLE
Code highlighting in VS Code (using Vetur for Vue) is funky

### ISSUE THREAD

**Issue by escapedcat** [sumcumo/nuxt-styleguide#8]
![image](https://user-images.githubusercontent.com/1016218/40490661-6d4a86de-5f6c-11e8-98fe-04912fa3aee4.png)

`<styleguide-states>` looks funny now.  
Nothing serious. Just opening this for transparency.

**Comment by Xiphe** [comment]
Vetur supports highlighting for custom blocks: https://github.com/vuejs/vetur/blob/master/docs/highlighting.md

But there seems to be an issue when the block starts with `style...` - so I added support for `nsg-`

So to get this to work you need to

1. install `nuxt-styleguide@v5.2.0`
2. Add this to your vscode config:
   ```json
   "vetur.grammar.customBlocks": {
        "nsg-doc": "md",
        "nsg-states": "js"
    }
   ```
3. Run the command "Vetur: Generate grammar from vetur.grammar.customBlocks" (via Command+Shift+P)
4. Close and re-open vscode
5. Refactor use of `styleguide-doc` to `nsg-doc`
6. Refactor use of `styleguide-states` to `nsg-states`
7. enjoy
